name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows-x64
          - os: ubuntu-latest
            platform: linux-x64
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make CFLAGS="-O2 -DNDEBUG" -j $(nproc)
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: save_edna
        path: save_edna-${{matrix.platform}}
        retention-days: 5
